import type { LevelDef } from './level.js';
import type {
  MoveToken,
  SolverStatus,
  SpaceProfile,
  V7Mechanic,
  ValidationMethod,
} from './types.js';

export interface V7LevelDef extends LevelDef {
  chapter: string;
  mechanics: V7Mechanic[];
  spaceProfile: SpaceProfile;
  par: number;
  solution: MoveToken[];
  solverStatus: SolverStatus;
  validationMethod: ValidationMethod;
}

type V7Input = Omit<V7LevelDef, 'levelDesignNote'> & {
  coreIdea: string;
  trick: string;
  fairness: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
};

function v7(input: V7Input): V7LevelDef {
  const {
    coreIdea,
    trick,
    fairness,
    difficulty,
    ...def
  } = input;
  return {
    ...def,
    levelDesignNote: {
      id: def.id,
      title: def.name,
      chapter: def.chapter,
      mechanics: def.mechanics,
      coreIdea,
      trick,
      fairness,
      difficulty,
      solverStatus: def.solverStatus,
      par: def.par,
      solution: def.solution,
    },
  };
}

export const V7_LEVEL_DEFS: V7LevelDef[] = [
  v7({
    id: 'v7-001',
    name: '点火格',
    subtitle: 'Ignition Cell',
    chapter: '第 1 章：启动序列',
    mechanics: ['core-push'],
    spaceProfile: 'open',
    par: 2,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '把能量核心推入发光接口。无人机只能推，不能穿过核心。',
    map: [
      '######',
      '#@ $.#',
      '######',
    ],
    solution: ['right', 'right'],
    coreIdea: 'Establish one push, one target, and immediate sci-fi object language.',
    trick: 'The only useful move is to approach from the left, making the push rule explicit.',
    fairness: 'All information is visible and the level is intentionally tiny.',
    difficulty: 1,
  }),
  v7({
    id: 'v7-002',
    name: '双轨供能',
    subtitle: 'Dual Feed',
    chapter: '第 1 章：启动序列',
    mechanics: ['core-push'],
    spaceProfile: 'dual-room',
    par: 8,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '########',
      '#@ $ .#',
      '#  $ .#',
      '########',
    ],
    solution: ['right', 'right', 'right', 'left', 'left', 'down', 'right', 'right'],
    coreIdea: 'Two cores share a narrow approach lane; the player must clear the upper lane first.',
    trick: 'Pushing the lower core first blocks access to the upper correction route.',
    fairness: 'The two interfaces sit in sight and the lane order is readable from the walls.',
    difficulty: 1,
  }),
  v7({
    id: 'v7-003',
    name: '反向电池',
    subtitle: 'Reverse Battery',
    chapter: '第 1 章：启动序列',
    mechanics: ['core-push'],
    spaceProfile: 'partitioned',
    par: 12,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '########',
      '# .  @#',
      '# $$  #',
      '# .   #',
      '########',
    ],
    solution: ['left', 'left', 'left', 'down', 'right', 'down', 'right', 'up', 'right', 'up', 'left', 'left'],
    coreIdea: 'Approach the same pair of cores from the opposite side to teach route planning.',
    trick: 'The drone starts on the apparent exit side, so the first pushes are setup moves.',
    fairness: 'Both goals and both cores are exposed; the route is not hidden.',
    difficulty: 2,
  }),
  v7({
    id: 'v7-004',
    name: '十字校准',
    subtitle: 'Cross Calibration',
    chapter: '第 1 章：启动序列',
    mechanics: ['core-push', 'misdirection'],
    spaceProfile: 'symmetric',
    par: 23,
    solverStatus: 'optimal',
    validationMethod: 'astar',
    intro: '',
    map: [
      '#######',
      '#  .  #',
      '# $ $ #',
      '#. @ .#',
      '# $ $ #',
      '#  .  #',
      '#######',
    ],
    solution: ['down', 'left', 'down', 'left', 'up', 'right', 'up', 'up', 'left', 'up', 'right', 'down', 'right', 'right', 'up', 'right', 'down', 'left', 'down', 'down', 'right', 'down', 'left'],
    coreIdea: 'A symmetric chamber asks the player to break symmetry in a deliberate order.',
    trick: 'Mirroring every move looks natural but strands one core against the side wall.',
    fairness: 'The deadlock risk is visible because every wall-adjacent target is open.',
    difficulty: 3,
  }),
  v7({
    id: 'v7-005',
    name: '核心偏置',
    subtitle: 'Core Offset',
    chapter: '第 1 章：启动序列',
    mechanics: ['core-push', 'misdirection'],
    spaceProfile: 'non-rectangular',
    par: 21,
    solverStatus: 'optimal',
    validationMethod: 'astar',
    intro: '',
    map: [
      '#########',
      '###   ###',
      '#  $ $  #',
      '# #. .# #',
      '#  $@$  #',
      '# #. .# #',
      '#   $   #',
      '##  .  ##',
      '#########',
    ],
    solution: ['up', 'left', 'down', 'right', 'up', 'right', 'down', 'left', 'down', 'down', 'up', 'up', 'up', 'up', 'up', 'right', 'down', 'left', 'up', 'left', 'down'],
    coreIdea: 'A non-rectangular lab bay turns basic pushing into a route-order puzzle.',
    trick: 'The central drone position invites an even split, but one core must be parked first.',
    fairness: 'Every pocket is visible and undo fully supports experimenting with order.',
    difficulty: 3,
  }),
  v7({
    id: 'v7-006',
    name: '单向折跃',
    subtitle: 'Portal Primer',
    chapter: '第 2 章：量子门',
    mechanics: ['quantum-portal'],
    spaceProfile: 'portal-linked',
    par: 4,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '量子门只传送无人机，不传送能量核心。用门绕到可推的一侧。',
    map: [
      '#########',
      '#@ o   #',
      '# ###  #',
      '# . $o #',
      '#########',
    ],
    solution: ['right', 'right', 'left', 'left'],
    coreIdea: 'Introduce player-only portals as a way to change approach side.',
    trick: 'Walking through the gate is useful only because the core cannot follow.',
    fairness: 'The paired portal glyphs are both visible and the target sits beside the core.',
    difficulty: 2,
  }),
  v7({
    id: 'v7-007',
    name: '双舱门',
    subtitle: 'Two Compartments',
    chapter: '第 2 章：量子门',
    mechanics: ['quantum-portal', 'core-push'],
    spaceProfile: 'multi-room',
    par: 14,
    solverStatus: 'optimal',
    validationMethod: 'astar',
    intro: '',
    map: [
      '##########',
      '#@       #',
      '# $ .  o #',
      '##########',
      '#  o     #',
      '# $ .    #',
      '##########',
    ],
    solution: ['down', 'right', 'right', 'up', 'right', 'right', 'down', 'right', 'right', 'left', 'left', 'down', 'right', 'right'],
    coreIdea: 'Two separated rooms force the player to solve one side, portal, then solve the other.',
    trick: 'The gate changes the player side, not the core lane.',
    fairness: 'The horizontal separation makes it clear that the portal is a route connector.',
    difficulty: 3,
  }),
  v7({
    id: 'v7-008',
    name: '深层折返',
    subtitle: 'Deep Foldback',
    chapter: '第 2 章：量子门',
    mechanics: ['quantum-portal', 'gate-circuit', 'misdirection'],
    spaceProfile: 'portal-linked',
    par: 29,
    solverStatus: 'optimal',
    validationMethod: 'astar',
    intro: '',
    map: [
      '############',
      '#@         #',
      '# $ .   o  #',
      '############',
      '#o         #',
      '# $ $ ^ .  #',
      '############',
    ],
    solution: ['down', 'right', 'right', 'up', 'right', 'right', 'down', 'right', 'right', 'right', 'right', 'right', 'down', 'right', 'right', 'left', 'left', 'up', 'left', 'left', 'left', 'right', 'down', 'right', 'right', 'right', 'right', 'right', 'right'],
    coreIdea: 'Portal routing combines with a sacrificial pit to create a multi-room order problem.',
    trick: 'A tempting early push toward the pit consumes the wrong resource.',
    fairness: 'The pit, remaining target, and portal pair are all visible before commitment.',
    difficulty: 4,
  }),
  v7({
    id: 'v7-009',
    name: '同步启动',
    subtitle: 'Synchronized Boot',
    chapter: '第 3 章：同步体',
    mechanics: ['sync-actors'],
    spaceProfile: 'dual-room',
    par: 2,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '同步关会同时驱动两块舱室；两边都完成，才算实验通过。',
    map: [
      '######',
      '#@ $.#',
      '######',
    ],
    twin: [
      '######',
      '#@ $.#',
      '######',
    ],
    solution: ['right', 'right'],
    coreIdea: 'Introduce one-input two-board play with identical boards.',
    trick: 'There is no trick yet; the goal is to make simultaneity legible.',
    fairness: 'Both chambers are identical and solved by the same visible action.',
    difficulty: 1,
  }),
  v7({
    id: 'v7-010',
    name: '镜像探针',
    subtitle: 'Mirror Probe',
    chapter: '第 3 章：同步体',
    mechanics: ['sync-actors', 'mirror-field'],
    spaceProfile: 'symmetric',
    par: 2,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '镜像同步体会左右反向响应同一次输入。看两边的推力方向，而不是只看无人机。',
    map: [
      '######',
      '#@ $.#',
      '######',
    ],
    twin: [
      '######',
      '#. $@#',
      '######',
    ],
    mirrorTwin: true,
    solution: ['right', 'right'],
    coreIdea: 'Use mirrored input so one command pushes opposite physical directions in two rooms.',
    trick: 'The right key moves the second drone left because that chamber is mirrored.',
    fairness: 'The rooms are symmetric and the intro names the mirror rule before use.',
    difficulty: 2,
  }),
  v7({
    id: 'v7-011',
    name: '双舱握手',
    subtitle: 'Twin Handshake',
    chapter: '第 3 章：同步体',
    mechanics: ['sync-actors', 'mirror-field', 'misdirection'],
    spaceProfile: 'dual-room',
    par: 4,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '',
    map: [
      '#####',
      '#@  #',
      '# $ #',
      '# . #',
      '#####',
    ],
    twin: [
      '#####',
      '#  @#',
      '# $ #',
      '# . #',
      '#####',
    ],
    solution: ['left', 'left', 'right', 'down'],
    coreIdea: 'One board may be blocked while the other moves; success is judged by both final states.',
    trick: 'The useful first inputs are inert on one side but position the other drone.',
    fairness: 'Blocked movement is visible and undo lets the player test lockstep behavior.',
    difficulty: 3,
  }),
  v7({
    id: 'v7-012',
    name: '残影门闩',
    subtitle: 'Echo Latch',
    chapter: '第 4 章：时间残影',
    mechanics: ['time-shadow', 'gate-circuit'],
    spaceProfile: 'partitioned',
    par: 6,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '残影会延迟复制无人机的位置。它能压住量子压板，也会挡住实体移动。',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '########',
      '#@ D $.#',
      '# 1    #',
      '########',
    ],
    solution: ['down', 'right', 'up', 'right', 'right', 'right'],
    coreIdea: 'Leave a one-step echo on the plate so the gate stays open while the drone returns to the corridor.',
    trick: 'Standing on the plate is not enough; the gate is one move away.',
    fairness: 'The plate, gate, and corridor distance are visible from the start.',
    difficulty: 2,
  }),
  v7({
    id: 'v7-013',
    name: '延迟电桥',
    subtitle: 'Delayed Bridge',
    chapter: '第 4 章：时间残影',
    mechanics: ['time-shadow', 'gate-circuit', 'core-push'],
    spaceProfile: 'partitioned',
    par: 7,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '#########',
      '#@ D $ .#',
      '# 1     #',
      '#########',
    ],
    solution: ['down', 'right', 'up', 'right', 'right', 'right', 'right'],
    coreIdea: 'The echo opens the gate, then the player must keep enough lane space to push the core twice.',
    trick: 'If the drone returns too early, its own echo becomes a blocker near the corridor.',
    fairness: 'The shadow is rendered and undoable; no hidden timing is involved.',
    difficulty: 3,
  }),
  v7({
    id: 'v7-014',
    name: '回声转角',
    subtitle: 'Echo Turn',
    chapter: '第 4 章：时间残影',
    mechanics: ['time-shadow', 'gate-circuit', 'misdirection'],
    spaceProfile: 'non-rectangular',
    par: 8,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '##########',
      '#@  D $ .#',
      '# 1      #',
      '##########',
    ],
    solution: ['right', 'right', 'down', 'right', 'right', 'up', 'right', 'right'],
    coreIdea: 'A corner route forces the player to set the echo, then approach the gate from a delayed angle.',
    trick: 'The shortest-looking line to the gate closes before the drone reaches it.',
    fairness: 'The plate is offset by a visible corner; the echo rule is already introduced.',
    difficulty: 3,
  }),
  v7({
    id: 'v7-015',
    name: '三拍锁',
    subtitle: 'Three-Tick Lock',
    chapter: '第 4 章：时间残影',
    mechanics: ['time-shadow', 'gate-circuit', 'misdirection'],
    spaceProfile: 'narrow',
    par: 8,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 2, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '##########',
      '#@  D $ .#',
      '#  1     #',
      '##########',
    ],
    solution: ['right', 'right', 'down', 'right', 'right', 'up', 'right', 'right'],
    coreIdea: 'A two-step delay changes the setup rhythm; the player must count the echo window.',
    trick: 'Repeating the one-step timing fails because the plate is held one beat later.',
    fairness: 'The level title, intro history, and visible shadow make the timing countable.',
    difficulty: 4,
  }),
];
