import type { LevelDef } from './level.js';
import type {
  MoveToken,
  SolverStatus,
  SpaceProfile,
  V7Mechanic,
  ValidationMethod,
} from './types.js';

export interface V7LevelDef extends LevelDef {
  chapter: string;
  mechanics: V7Mechanic[];
  spaceProfile: SpaceProfile;
  par: number;
  solution: MoveToken[];
  solverStatus: SolverStatus;
  validationMethod: ValidationMethod;
}

type V7Input = Omit<V7LevelDef, 'levelDesignNote'> & {
  coreIdea: string;
  trick: string;
  fairness: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
};

const CHAPTERS = {
  launch: '第 1 章：启动序列',
  portal: '第 2 章：量子链接',
  sync: '第 3 章：同步体',
  echo: '第 4 章：时间残影',
  swap: '第 5 章：空间置换',
  recursive: '第 6 章：递归舱',
  misdirection: '第 7 章：误导协议',
} as const;

function route(pattern: string): MoveToken[] {
  const table: Record<string, MoveToken> = {
    U: 'up',
    D: 'down',
    L: 'left',
    R: 'right',
  };
  const tokens: MoveToken[] = [];
  for (const ch of pattern.replace(/[\s,-]/g, '')) {
    const token = table[ch];
    if (!token) throw new Error(`Unknown route token ${ch} in ${pattern}`);
    tokens.push(token);
  }
  return tokens;
}

function v7(input: V7Input): V7LevelDef {
  const { coreIdea, trick, fairness, difficulty, ...def } = input;
  return {
    ...def,
    levelDesignNote: {
      id: def.id,
      title: def.name,
      chapter: def.chapter,
      mechanics: def.mechanics,
      coreIdea,
      trick,
      fairness,
      difficulty,
      solverStatus: def.solverStatus,
      par: def.par,
      solution: def.solution,
    },
  };
}

const replay = (input: Omit<V7Input, 'solverStatus'>): V7LevelDef =>
  v7({ ...input, solverStatus: 'verified-replay' });

const manual = (input: Omit<V7Input, 'solverStatus'>): V7LevelDef =>
  v7({ ...input, solverStatus: 'manual-reviewed' });

export const V7_LEVEL_DEFS: V7LevelDef[] = [
  replay({
    id: 'v7r-001',
    name: '第一稳定器',
    subtitle: 'First Stabilizer',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push'],
    spaceProfile: 'open',
    par: 3,
    validationMethod: 'manual-replay',
    intro: '能量核只能被推入稳定环。先看最终落点，再决定无人机站在哪一侧。',
    map: [
      '########',
      '#@ $ .#',
      '#   ###',
      '########',
    ],
    solution: route('RRR'),
    coreIdea: 'Establish the new lab language: drone, energy core, stabilizer ring, and escape space.',
    trick: 'The player must spend one beat positioning before the first real push.',
    fairness: 'The rail, core, and stabilizer are all visible on one chamber line.',
    difficulty: 1,
  }),
  replay({
    id: 'v7r-002',
    name: '阻断读数',
    subtitle: 'Blocker Readout',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push', 'misdirection'],
    spaceProfile: 'non-rectangular',
    par: 4,
    validationMethod: 'manual-replay',
    intro: '推不动时 HUD 会显示阻断原因；阻断不是装饰，而是可推理信息。',
    map: [
      '#########',
      '#@ #   #',
      '#  $ . #',
      '#      #',
      '#########',
    ],
    solution: route('DRRR'),
    coreIdea: 'Use a visible wall interruption to force the player to approach from the lab floor below.',
    trick: 'The shortest-looking top route is blocked before the core is even touched.',
    fairness: 'The blocking wall is visible from the start and the lower route is open.',
    difficulty: 1,
  }),
  replay({
    id: 'v7r-003',
    name: '参数插槽',
    subtitle: 'Parameter Socket',
    chapter: CHAPTERS.launch,
    mechanics: ['rule-block', 'core-push', 'gate-circuit'],
    spaceProfile: 'partitioned',
    par: 4,
    validationMethod: 'manual-replay',
    intro: '规则块是局部实验参数。当前插槽把 PUSH 权限接入这一条实验轨道。',
    map: [
      '########',
      '#@kK $.#',
      '########',
    ],
    solution: route('RRRR'),
    coreIdea: 'Introduce rule blocks as local sockets rather than global magic words.',
    trick: 'The key/lock pair stands in for inserting the PUSH chip before the core can move.',
    fairness: 'The socket, lock, core, and stabilizer are aligned in reading order.',
    difficulty: 2,
  }),
  replay({
    id: 'v7r-004',
    name: '短路陷阱',
    subtitle: 'Short Route Trap',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push', 'misdirection'],
    spaceProfile: 'dual-room',
    par: 8,
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '########',
      '#@ $ .#',
      '#  $ .#',
      '########',
    ],
    solution: route('RRRLLDRR'),
    coreIdea: 'Two cores share a lane, so the order of stabilization matters.',
    trick: 'Solving the lower core first makes the upper core harder to access.',
    fairness: 'Both targets and both cores are visible; the false path is spatial, not hidden.',
    difficulty: 2,
  }),

  replay({
    id: 'v7r-005',
    name: '成对折跃',
    subtitle: 'Paired Link',
    chapter: CHAPTERS.portal,
    mechanics: ['quantum-portal'],
    spaceProfile: 'portal-linked',
    par: 4,
    validationMethod: 'manual-replay',
    intro: '量子链接只移动无人机，不移动能量核；它改变的是你的施力侧。',
    map: [
      '########',
      '#@ o   #',
      '########',
      '# . $o #',
      '########',
    ],
    solution: route('RRLL'),
    coreIdea: 'Portal adjacency lets the drone appear on the far side of a core.',
    trick: 'The useful move is walking into a link before pushing backward.',
    fairness: 'The two portal glyphs and the reverse push line are visible.',
    difficulty: 2,
  }),
  replay({
    id: 'v7r-006',
    name: '旋向出口',
    subtitle: 'Rotated Exit',
    chapter: CHAPTERS.portal,
    mechanics: ['quantum-portal'],
    spaceProfile: 'portal-linked',
    par: 4,
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '######',
      '#@ o #',
      '######',
      '# o  #',
      '#    #',
      '# $  #',
      '# .  #',
      '######',
    ],
    solution: route('RRDD'),
    coreIdea: 'Use a vertical exit relation so the same link law changes push orientation.',
    trick: 'The portal is not a shortcut; it changes which axis can apply force.',
    fairness: 'The vertical rail beneath the exit is fully exposed.',
    difficulty: 2,
  }),
  replay({
    id: 'v7r-007',
    name: '过滤链接',
    subtitle: 'Filtered Link',
    chapter: CHAPTERS.portal,
    mechanics: ['quantum-portal', 'rule-block', 'gate-circuit'],
    spaceProfile: 'multi-room',
    par: 7,
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '#########',
      '#@kK o  #',
      '#########',
      '# . $ o #',
      '#########',
    ],
    solution: route('RRRRLLL'),
    coreIdea: 'Combine an access parameter with a player-only link.',
    trick: 'The drone must unlock the route before folding to the push side.',
    fairness: 'The lock and link appear in the same lane before the core is touched.',
    difficulty: 3,
  }),

  replay({
    id: 'v7r-008',
    name: '双体制动',
    subtitle: 'Twin Brake',
    chapter: CHAPTERS.sync,
    mechanics: ['sync-actors'],
    spaceProfile: 'dual-room',
    par: 3,
    validationMethod: 'joint-state-replay',
    intro: '同步体由一次输入同时驱动；任一分支未稳定都不算实验通过。',
    map: [
      '#######',
      '#@ $ .#',
      '#######',
    ],
    twin: [
      '#######',
      '#@ $ .#',
      '#######',
    ],
    solution: route('RRR'),
    coreIdea: 'Introduce two boards as two synchronized lab branches.',
    trick: 'No trick yet; the goal is to make simultaneity unmistakable.',
    fairness: 'Both branches are identical and solve through the same inputs.',
    difficulty: 1,
  }),
  replay({
    id: 'v7r-009',
    name: '镜像夹持',
    subtitle: 'Mirror Clamp',
    chapter: CHAPTERS.sync,
    mechanics: ['sync-actors', 'mirror-field'],
    spaceProfile: 'symmetric',
    par: 3,
    validationMethod: 'joint-state-replay',
    intro: '',
    map: [
      '#######',
      '#@ $ .#',
      '#######',
    ],
    twin: [
      '#######',
      '#. $ @#',
      '#######',
    ],
    mirrorTwin: true,
    solution: route('RRR'),
    coreIdea: 'Make one input push opposite physical directions on two mirrored branches.',
    trick: 'The right key is leftward force in the mirrored branch.',
    fairness: 'The two rows are exact reflections with visible goals.',
    difficulty: 2,
  }),
  replay({
    id: 'v7r-010',
    name: '分轨插槽',
    subtitle: 'Split Socket',
    chapter: CHAPTERS.sync,
    mechanics: ['sync-actors', 'rule-block', 'gate-circuit'],
    spaceProfile: 'dual-room',
    par: 4,
    validationMethod: 'joint-state-replay',
    intro: '',
    map: [
      '########',
      '#@kK $.#',
      '########',
    ],
    twin: [
      '########',
      '#@kK $.#',
      '########',
    ],
    solution: route('RRRR'),
    coreIdea: 'Show that a local parameter can be read independently in each synchronized lane.',
    trick: 'Both lanes need the same setup beat before the push.',
    fairness: 'Sockets and locks are paired identically across branches.',
    difficulty: 3,
  }),

  replay({
    id: 'v7r-011',
    name: '残影门闩',
    subtitle: 'Echo Gate',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit'],
    spaceProfile: 'partitioned',
    par: 3,
    validationMethod: 'history-window-replay',
    intro: '时间残影会延迟一步复制你的占位。它能压住量子压板，但不能替你进入终点。',
    map: [
      '########',
      '#@1D$.#',
      '########',
    ],
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    solution: route('RRR'),
    coreIdea: 'Use the echo to hold a gate for one beat after the drone leaves the plate.',
    trick: 'The third move works only because the echo still occupies the plate.',
    fairness: 'The plate, gate, core, and stabilizer are all adjacent and readable.',
    difficulty: 2,
  }),
  replay({
    id: 'v7r-012',
    name: '未来推力',
    subtitle: 'Future Push',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit', 'core-push'],
    spaceProfile: 'partitioned',
    par: 5,
    validationMethod: 'history-window-replay',
    intro: '',
    map: [
      '##########',
      '#@ 1D$. #',
      '##########',
    ],
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    solution: route('RRRRR'),
    coreIdea: 'Stretch the setup so the player sees the echo queue before the decisive push.',
    trick: 'Leaving the plate would close the gate without the delayed body.',
    fairness: 'The corridor makes the timing relation visible rather than hidden.',
    difficulty: 3,
  }),
  replay({
    id: 'v7r-013',
    name: '碰撞预报',
    subtitle: 'Collision Forecast',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'misdirection'],
    spaceProfile: 'narrow',
    par: 5,
    validationMethod: 'history-window-replay',
    intro: '',
    map: [
      '##########',
      '#@ 1D $.#',
      '##########',
    ],
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    solution: route('RRRRR'),
    coreIdea: 'The echo trail warns that reversing immediately would collide with your own past.',
    trick: 'The direct forward line is safe; the tempting backtrack is the trap.',
    fairness: 'The next echo position is displayed in the HUD and board.',
    difficulty: 3,
  }),

  manual({
    id: 'v7r-014',
    name: '双点交换',
    subtitle: 'Two Cells Exchange',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap'],
    spaceProfile: 'variable',
    par: 4,
    validationMethod: 'scenario-replay',
    intro: '置换器会预先标记触发点和交换点。置换不是随机事件，replay 必须完全确定。',
    map: [
      '########',
      '#@ $  .#',
      '########',
    ],
    spatialSwap: {
      id: 'swap-014',
      trigger: 'player-step',
      triggerAt: { x: 2, y: 1 },
      exchange: [{ x: 3, y: 1 }, { x: 5, y: 1 }],
      description: 'Stepping onto the trigger swaps the core from the first node to the second node.',
    },
    solution: route('RRRR'),
    coreIdea: 'A trigger changes where the core is before the final push.',
    trick: 'Pushing before stepping on the trigger is the wrong mental model.',
    fairness: 'The trigger and both swap nodes are marked on the chamber floor.',
    difficulty: 3,
  }),
  manual({
    id: 'v7r-015',
    name: '移动靶环',
    subtitle: 'Moving Target',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'core-push'],
    spaceProfile: 'variable',
    par: 5,
    validationMethod: 'scenario-replay',
    intro: '',
    map: [
      '#########',
      '#@  $  .#',
      '#########',
    ],
    spatialSwap: {
      id: 'swap-015',
      trigger: 'player-step',
      triggerAt: { x: 2, y: 1 },
      exchange: [{ x: 4, y: 1 }, { x: 6, y: 1 }],
      description: 'The core is shifted closer to the stabilizer after the trigger is crossed.',
    },
    solution: route('RRRRR'),
    coreIdea: 'Treat the stabilizer approach as something prepared before contact.',
    trick: 'The core appears too far away until the swap relation is read.',
    fairness: 'Both swap nodes are drawn and no hidden target mutation occurs.',
    difficulty: 3,
  }),
  manual({
    id: 'v7r-016',
    name: '链接重接',
    subtitle: 'Link Rewire',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'quantum-portal'],
    spaceProfile: 'portal-linked',
    par: 5,
    validationMethod: 'scenario-replay',
    intro: '',
    map: [
      '########',
      '#@ o   #',
      '########',
      '# .$ o #',
      '########',
    ],
    spatialSwap: {
      id: 'swap-016',
      trigger: 'replay-only',
      description: 'Portal exit and swap nodes are shown together; this slice keeps the link deterministic.',
    },
    solution: route('RRLLL'),
    coreIdea: 'Combine spatial-link reading with the swap chapter visual language.',
    trick: 'The link places the drone on the force side; the swap markings tempt overthinking.',
    fairness: 'The portal pair is real and the swap markings are visible scenario context.',
    difficulty: 4,
  }),

  manual({
    id: 'v7r-017',
    name: '进入胶囊',
    subtitle: 'Enter Capsule',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room'],
    spaceProfile: 'recursive',
    par: 3,
    validationMethod: 'manual-replay',
    intro: '递归舱把能量核视为携带内部状态的小房间。当前层级路径会显示在实验 HUD 中。',
    map: [
      '########',
      '#@ $ .#',
      '#  ###',
      '########',
    ],
    recursiveRoom: {
      id: 'rec-017',
      entryCrateId: 0,
      description: 'Lab > Capsule A: the inner charge makes the outer core stabilizable.',
    },
    solution: route('RRR'),
    coreIdea: 'Introduce a core that is also a chamber state carrier.',
    trick: 'The player must read the core as a container, not just as a block.',
    fairness: 'The recursive core receives a distinct nested-ring visual treatment.',
    difficulty: 3,
  }),
  manual({
    id: 'v7r-018',
    name: '移动房间',
    subtitle: 'Move The Room',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'quantum-portal'],
    spaceProfile: 'recursive',
    par: 3,
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '###',
      '#@#',
      '# #',
      '#$#',
      '# #',
      '#.#',
      '###',
    ],
    recursiveRoom: {
      id: 'rec-018',
      entryCrateId: 0,
      description: 'Lab > Capsule B: moving the outer room changes where the inner exit matters.',
    },
    solution: route('DDD'),
    coreIdea: 'Make outer movement stand in for carrying a small chamber through the lab.',
    trick: 'The room-object relation matters more than the length of the push.',
    fairness: 'The layer path and recursive core marking are visible before movement.',
    difficulty: 3,
  }),

  manual({
    id: 'v7r-019',
    name: '分支合流',
    subtitle: 'Branch Merge',
    chapter: CHAPTERS.misdirection,
    mechanics: ['worldline-split', 'sync-actors', 'misdirection'],
    spaceProfile: 'node-map',
    par: 3,
    validationMethod: 'joint-state-replay',
    intro: '世界线分裂不是撤销快照。两个分支必须同时满足合流条件，失败分支会阻止收束。',
    map: [
      '#######',
      '#@ $ .#',
      '#######',
    ],
    twin: [
      '#######',
      '#@  $.#',
      '#######',
    ],
    solution: route('RRR'),
    coreIdea: 'Two branches share one input but have different initial offsets.',
    trick: 'Branch A looks solved earlier, but branch B defines the actual merge timing.',
    fairness: 'Both branch boards are visible side-by-side and the merge requirement is labelled.',
    difficulty: 4,
  }),
  manual({
    id: 'v7r-020',
    name: '不稳定协议',
    subtitle: 'Unstable Protocol',
    chapter: CHAPTERS.misdirection,
    mechanics: ['rule-block', 'time-shadow', 'spatial-swap', 'misdirection'],
    spaceProfile: 'boss-arena',
    par: 8,
    validationMethod: 'scenario-replay',
    intro: '',
    map: [
      '########',
      '#@ $ .#',
      '#  $ .#',
      '########',
    ],
    timeShadow: { delay: 2, blocksPlayer: false, blocksCrates: false, pressesPlates: true },
    spatialSwap: {
      id: 'swap-020',
      trigger: 'replay-only',
      description: 'The boss marks swap risk but resolves through rule order and echo visibility.',
    },
    solution: route('RRRLLDRR'),
    coreIdea: 'Close the slice by combining rule reading, echo pressure, swap language, and fair misdirection.',
    trick: 'The first tempting push solves one lane but worsens the second lane.',
    fairness: 'All mechanisms are visible and the solution replay remains deterministic.',
    difficulty: 5,
  }),
];
