import type { PuzzleId } from './types';

export interface T32HardRebuildWitness {
  id: PuzzleId;
  firstDivergenceLock: number;
  primary: { locks: number; commandStream: string };
  alternate: { locks: number; commandStream: string };
}

export const T32_HARD_REBUILD_WITNESSES = Object.freeze([
  {
    id: 'tm-puzzle-46',
    firstDivergenceLock: 1,
    primary: {
      locks: 16,
      commandStream: 'SRRHTTTCRRRHTTTRHTTTCRRRRHTTTCCLLLHTTTTTTTTTTTTCCCHTTTTTTTTTTTTCLLLLLHTTTCCLLHTTTTTTTTTTTTCCLLHTTTTTTTTTTTTRRHTTTTTTTTTTTTCRRRRHTTTTTTTTTTTTLLLLHTTTCLHTTTCRRRHTTTCCCLLHTTTTTTTTTTTTCCRHTTTTTTTTTTTT',
    },
    alternate: {
      locks: 16,
      commandStream: 'SCLLLLHTTTLHTTTRRRRHTTTCRHTTTCCCRRRHTTTTTTTTTTTTCLLHTTTCLLLLLHTTTTTTTTTTTTCHTTTTTTTTTTTTCCCLLLHTTTLLHTTTCLLLLLHTTTRRHTTTTTTTTTTTTCRRRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTCCCHTTTCRRHTTTTTTTTTTTT',
    },
  },
  {
    id: 'tm-puzzle-48',
    firstDivergenceLock: 2,
    primary: {
      locks: 19,
      commandStream: 'SCCCRRRRRHTTTCRRRRHTTTLLLHTTTCLHTTTTTTTTTTTTLLLHTTTCLLLLHTTTCCCRHTTTTTTTTTTTTLHTTTRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTLLLHTTTCCRRRRHTTTTTTTTTTTTCCLHTTTCLLLLHTTTRHTTTTTTTTTTTTCCRRRRHTTTTTTTTTTTTCRRRHTTTTTTTTTTTTCCCLHTTTCHTTTTTTTTTTTT',
    },
    alternate: {
      locks: 20,
      commandStream: 'SCCCRRRRRHTTTLHTTTRRHTTTCLHTTTLLLLHTTTTTTTTTTTTCCLLLHTTTTTTTTTTTTCCCRHTTTTTTTTTTTTCCCRRRHTTTRRRRHTTTTTTTTTTTTCRHTTTLLLHTTTTTTTTTTTTCCLLLHTTTTTTTTTTTTCCLLHTTTCLLLLHTTTHTTTCCRRRRHTTTTTTTTTTTTCRRRHTTTTTTTTTTTTCCCRRRRRHTTTTTTTTTTTTCHTTTCLHTTTTTTTTTTTT',
    },
  },
  {
    id: 'tm-puzzle-49',
    firstDivergenceLock: 1,
    primary: {
      locks: 17,
      commandStream: 'SCCCHTTTCRHTTTLLLLHTTTCLLLHTTTTTTTTTTTTRRRRHTTTTTTTTTTTTCLHTTTTTTTTTTTTLHTTTCRRRRHTTTRRRHTTTTTTTTTTTTCRRHTTTCLLLLHTTTTTTTTTTTTCCCRRRRHTTTCCCRHTTTTTTTTTTTTHTTTCLLLLHTTTTTTTTTTTTCRRHTTTTTTTTTTTTCLLHTTTTTTTTTTTT',
    },
    alternate: {
      locks: 19,
      commandStream: 'SRHTTTCLLHTTTLLLLHTTTTTTTTTTTTCLHTTTRRRRHTTTTTTTTTTTTCCCRRRHTTTCRRRRHTTTCLLHTTTTTTTTTTTTCRHTTTHTTTCLLLLHTTTTTTTTTTTTCCCLLHTTTCCRRRHTTTRRHTTTCLLLLHTTTTTTTTTTTTCCCRRRRRHTTTTTTTTTTTTCHTTTTTTTTTTTTCLLLLHTTTCCCLHTTTTTTTTTTTT',
    },
  },
  {
    id: 'tm-puzzle-50',
    firstDivergenceLock: 3,
    primary: {
      locks: 19,
      commandStream: 'SCLLLHTTTCLHTTTCCRRRRHTTTTTTTTTTTTCLLLLLHTTTTTTTTTTTTCCHTTTCCCLLLHTTTRRRRHTTTCCCRRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTCLLHTTTTTTTTTTTTCLLLHTTTCHTTTTTTTTTTTTRRRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTRRHTTTCLLLLHTTTTTTTTTTTTCRHTTTCCCHTTTCCCRRRRRHTTTTTTTTTTTT',
    },
    alternate: {
      locks: 20,
      commandStream: 'SCLLLHTTTCLHTTTCLLLLHTTTCRRRRHTTTTTTTTTTTTCRRRHTTTTTTTTTTTTRHTTTLLLLHTTTHTTTCRRRHTTTTTTTTTTTTCLLHTTTTTTTTTTTTCLHTTTTTTTTTTTTCCRRHTTTRRRRHTTTTTTTTTTTTRRRRHTTTRHTTTLLLHTTTTTTTTTTTTCLLHTTTTTTTTTTTTCCCLLLHTTTTTTTTTTTTCHTTTCRRRRHTTTTTTTTTTTT',
    },
  },
] as const satisfies readonly T32HardRebuildWitness[]);
