import { describe, expect, it } from 'vitest';
import { replayPuzzleRoute } from './puzzleRouteSearch';
import type { PuzzleId } from './types';

const STRICT_REBUILD_WITNESSES = [
  {
    id: 'tm-puzzle-46',
    locks: 16,
    route: 'SRRHTTTCRRRHTTTRHTTTCRRRRHTTTCCLLLHTTTTTTTTTTTTCCCHTTTTTTTTTTTTCLLLLLHTTTCCLLHTTTTTTTTTTTTCCLLHTTTTTTTTTTTTRRHTTTTTTTTTTTTCRRRRHTTTTTTTTTTTTLLLLHTTTCLHTTTCRRRHTTTCCCLLHTTTTTTTTTTTTCCRHTTTTTTTTTTTT',
  },
  {
    id: 'tm-puzzle-48',
    locks: 19,
    route: 'SCCCRRRRRHTTTCRRRRHTTTLLLHTTTCLHTTTTTTTTTTTTLLLHTTTCLLLLHTTTCCCRHTTTTTTTTTTTTLHTTTRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTLLLHTTTCCRRRRHTTTTTTTTTTTTCCLHTTTCLLLLHTTTRHTTTTTTTTTTTTCCRRRRHTTTTTTTTTTTTCRRRHTTTTTTTTTTTTCCCLHTTTCHTTTTTTTTTTTT',
  },
  {
    id: 'tm-puzzle-49',
    locks: 17,
    route: 'SCCCHTTTCRHTTTLLLLHTTTCLLLHTTTTTTTTTTTTRRRRHTTTTTTTTTTTTCLHTTTTTTTTTTTTLHTTTCRRRRHTTTRRRHTTTTTTTTTTTTCRRHTTTCLLLLHTTTTTTTTTTTTCCCRRRRHTTTCCCRHTTTTTTTTTTTTHTTTCLLLLHTTTTTTTTTTTTCRRHTTTTTTTTTTTTCLLHTTTTTTTTTTTT',
  },
  {
    id: 'tm-puzzle-50',
    locks: 19,
    route: 'SCLLLHTTTCLHTTTCCRRRRHTTTTTTTTTTTTCLLLLLHTTTTTTTTTTTTCCHTTTCCCLLLHTTTRRRRHTTTCCCRRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTCLLHTTTTTTTTTTTTCLLLHTTTCHTTTTTTTTTTTTRRRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTRRHTTTCLLLLHTTTTTTTTTTTTCRHTTTCCCHTTTCCCRRRRRHTTTTTTTTTTTT',
  },
] as const satisfies ReadonlyArray<{ id: PuzzleId; locks: number; route: string }>;

describe('T32 strict Hard rebuild witnesses', () => {
  it.each(STRICT_REBUILD_WITNESSES)('$id finishes through public Core commands', ({ id, locks, route }) => {
    const replay = replayPuzzleRoute(id, route);
    expect(replay.locks).toHaveLength(locks);
    expect(replay.state.puzzleCompletion).toBe('finished');
  });
});
