import { describe, expect, it } from 'vitest';
import { replayPuzzleRoute } from './puzzleRouteSearch';
import type { PuzzleId } from './types';

const STRICT_REBUILD_WITNESSES = [
  {
    id: 'tm-puzzle-46',
    locks: 16,
    route: 'SRRHTTTCRRRHTTTRHTTTCRRRRHTTTCCLLLHTTTTTTTTTTTTCCCHTTTTTTTTTTTTCLLLLLHTTTCCLLHTTTTTTTTTTTTCCLLHTTTTTTTTTTTTRRHTTTTTTTTTTTTCRRRRHTTTTTTTTTTTTLLLLHTTTCLHTTTCRRRHTTTCCCLLHTTTTTTTTTTTTCCRHTTTTTTTTTTTT',
    alternateLocks: 16,
    alternate: 'SCLLLLHTTTLHTTTRRRRHTTTCRHTTTCCCRRRHTTTTTTTTTTTTCLLHTTTCLLLLLHTTTTTTTTTTTTCHTTTTTTTTTTTTCCCLLLHTTTLLHTTTCLLLLLHTTTRRHTTTTTTTTTTTTCRRRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTCCCHTTTCRRHTTTTTTTTTTTT',
  },
  {
    id: 'tm-puzzle-48',
    locks: 19,
    route: 'SCCCRRRRRHTTTCRRRRHTTTLLLHTTTCLHTTTTTTTTTTTTLLLHTTTCLLLLHTTTCCCRHTTTTTTTTTTTTLHTTTRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTLLLHTTTCCRRRRHTTTTTTTTTTTTCCLHTTTCLLLLHTTTRHTTTTTTTTTTTTCCRRRRHTTTTTTTTTTTTCRRRHTTTTTTTTTTTTCCCLHTTTCHTTTTTTTTTTTT',
    alternateLocks: 20,
    alternate: 'SCCCRRRRRHTTTLHTTTRRHTTTCLHTTTLLLLHTTTTTTTTTTTTCCLLLHTTTTTTTTTTTTCCCRHTTTTTTTTTTTTCCCRRRHTTTRRRRHTTTTTTTTTTTTCRHTTTLLLHTTTTTTTTTTTTCCLLLHTTTTTTTTTTTTCCLLHTTTCLLLLHTTTHTTTCCRRRRHTTTTTTTTTTTTCRRRHTTTTTTTTTTTTCCCRRRRRHTTTTTTTTTTTTCHTTTCLHTTTTTTTTTTTT',
  },
  {
    id: 'tm-puzzle-49',
    locks: 17,
    route: 'SCCCHTTTCRHTTTLLLLHTTTCLLLHTTTTTTTTTTTTRRRRHTTTTTTTTTTTTCLHTTTTTTTTTTTTLHTTTCRRRRHTTTRRRHTTTTTTTTTTTTCRRHTTTCLLLLHTTTTTTTTTTTTCCCRRRRHTTTCCCRHTTTTTTTTTTTTHTTTCLLLLHTTTTTTTTTTTTCRRHTTTTTTTTTTTTCLLHTTTTTTTTTTTT',
    alternateLocks: 19,
    alternate: 'SRHTTTCLLHTTTLLLLHTTTTTTTTTTTTCLHTTTRRRRHTTTTTTTTTTTTCCCRRRHTTTCRRRRHTTTCLLHTTTTTTTTTTTTCRHTTTHTTTCLLLLHTTTTTTTTTTTTCCCLLHTTTCCRRRHTTTRRHTTTCLLLLHTTTTTTTTTTTTCCCRRRRRHTTTTTTTTTTTTCHTTTTTTTTTTTTCLLLLHTTTCCCLHTTTTTTTTTTTT',
  },
  {
    id: 'tm-puzzle-50',
    locks: 19,
    route: 'SCLLLHTTTCLHTTTCCRRRRHTTTTTTTTTTTTCLLLLLHTTTTTTTTTTTTCCHTTTCCCLLLHTTTRRRRHTTTCCCRRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTCLLHTTTTTTTTTTTTCLLLHTTTCHTTTTTTTTTTTTRRRRHTTTTTTTTTTTTRRHTTTTTTTTTTTTRRHTTTCLLLLHTTTTTTTTTTTTCRHTTTCCCHTTTCCCRRRRRHTTTTTTTTTTTT',
    alternateLocks: 20,
    alternate: 'SCLLLHTTTCLHTTTCLLLLHTTTCRRRRHTTTTTTTTTTTTCRRRHTTTTTTTTTTTTRHTTTLLLLHTTTHTTTCRRRHTTTTTTTTTTTTCLLHTTTTTTTTTTTTCLHTTTTTTTTTTTTCCRRHTTTRRRRHTTTTTTTTTTTTRRRRHTTTRHTTTLLLHTTTTTTTTTTTTCLLHTTTTTTTTTTTTCCCLLLHTTTTTTTTTTTTCHTTTCRRRRHTTTTTTTTTTTT',
  },
] as const satisfies ReadonlyArray<{
  id: PuzzleId;
  locks: number;
  route: string;
  alternateLocks: number;
  alternate: string;
}>;

describe('T32 strict Hard rebuild witnesses', () => {
  it.each(STRICT_REBUILD_WITNESSES)('$id finishes through two divergent public-Core routes', ({
    id, locks, route, alternateLocks, alternate,
  }) => {
    const canonical = replayPuzzleRoute(id, route);
    const divergent = replayPuzzleRoute(id, alternate);
    expect(canonical.locks).toHaveLength(locks);
    expect(divergent.locks).toHaveLength(alternateLocks);
    expect(canonical.state.puzzleCompletion).toBe('finished');
    expect(divergent.state.puzzleCompletion).toBe('finished');
    const firstDivergence = canonical.locks.findIndex(
      (lock, index) => lock.signature !== divergent.locks[index]?.signature,
    );
    expect(firstDivergence).toBeGreaterThanOrEqual(0);
  });
});
